# Promise对象<br/>
[promise语法](http://es6.ruanyifeng.com/#docs/promise)

## Promise的含义：
1. Promise是什么？<br/>
    + 是一个容器，里面保存着某个未来才会结束的事件（通常是一个异步操作）的结果。
    + 语法上，是一个对象，可获取异步操作的消息。
2. Promise对象的两个特点：
    + Promise对象的状态不受外界影响。有三种状态：pending（进行中），fulfilled（已成功）和rejected（已失败）。
    + 状态改变之后，就不会再变。状态改变有两种：pending变为fulfilled，或者pending变为rejected。这两种情况中，任何一种情况发生，状态就凝固了，不会再变，会一直保持这个结果，称为resolved(已定型)。
3. Promise对象的缺点：
    + 无法取消Promise，一旦新建，不能中途取消
    + 如果不设置回调函数(catch)，Promise内部抛出的错误，不会反映到外部
    + 处于pending状态时，无法得知进展到哪一步

## Promise的用法：
1. 新建一个promise实例，并做出各部分内容解释
    <pre>
    const newPromise = new Promise(function(resolve,reject){
        getUserInfo(state.token).then(response => {
            //异步操作成功
          resolve(response)
        }).catch(error => {
            //异步操作失败
          reject(error)
        })
    })</pre>
    * 说明如下    
    1. Promise作为构造函数，参数是个函数function，函数有两个参数resolve和reject，resolve和reject也是函数
    2. resolve在异步操作成功时调用，将newPromise的状态从pending变为resolved，并将异步操作的结果，作为参数传递出去
    3，reject在异步操作失败时调用，将newPromise的状态从pending变为rejected，并将异步操作的报错，作为参数传递出去。
2. Promise实例生成后，怎样获取其改变后的状态？Promise什么时候执行？then中回调函数什么时候执行？
    1. 用<font color=#FF5983>then方法</font>接收回调函数作为从参数。第一个函数是resolved的回调函数，第二个是rejected的回调函数。then里面，第二个参数可选。
        <pre>
        promise.then(function(value1){
            //success,fulfilled，value1是resolve传出的值
        },function(error1){
            //failure,rejected，error1是reject传出的值
        })
        //如果是then().catch()，then里面是resolve回调函数，catch里是reject回调函数</pre>
        
    2. Promise在创建后，立即执行。(可能是因为这个原因，Promise实例通常是在return中作为返回值出现)。
    3. Promise实例的<font color="#FF5983">状态发生改变后</font>(fulfilled 或 rejected)，就会触发then方法绑定的回调函数。
3. Promise实例的第一个参数（resolve函数）和第二个参数（reject函数），一般是什么值？
    + resolve函数可以不带参数，直接写成resolve()，也可以带参数，带的话，可以是<font color="#FF5983">正常值</font>，也可以是<font color="#FF5983">另一个Promise实例</font>。
    + reject函数也可以不带参数，直接写成reject(),如果带参数，通常是Error对象实例
4. Promise如何结束？
    + Promise实例中的参数（function(resolve,reject)）执行完时
    + resolve或者reject函数执行完，Promise并不会结束，所以最好不要在resolve或reject后面写语句
    + 最好用类似于`return resolve(someCode);`的方式结束Promise

## Promise.prototype.then()
1. then方法的参数是promise实例状态改变时的回调函数，分别是resolved和rejected (前面有写)。
2. <font color="#FF5983">第一个then方法返回的是一个新Promise实例</font>，so可以用链式写法，在后面跟第二个then。此时，第一个then里的return结果，会作为第二个then里的回调函数参数。
3. 分析下面的链式写法then的执行
    <pre>
    getJSON("/post/1.json").then(
        post => getJSON(post.commentURL)
    ).then(
        comments => console.log("resolved: ", comments),
        err => console.log("rejected: ", err)
    );
    </pre>
    * 第一个then返回(另)一个Promise实例，接着这个实例作为输入，进入第二个then
    * 第二个then中，等待这个新的Promise实例状态发生变化时执行
    * 如果resolved就执行59行，如果rejected就执行60行

## Promise.prototype.catch()
1. Promise.prototype.catch() 什么时候用？用在什么地方？
    1. 指定发生错误时的回调函数
    2. 两种错误可以被catch到：
        * Promise实例状态变为rejected时，会调用catch方法指定回调函数（reject方法的作用，等同于抛出错误）
        * then方法里的回调函数，运行中抛出的错误，也能被catch住
2. 关于捕获异常有哪些点？
    1. Promise对象的错误具有冒泡性质，会一直向后传递，直到捕获为止。错误总会被下一个catch语句捕获。
    2. 由于这个冒泡性质，reject状态的回调不要写在then里。而要用then().catch,因为catch不仅能捕获reject，也能捕获then里的异常。
3. 没有用catch方法指定错误处理的回调函数，会怎样？
    + Promise对象抛出的错误不会传递到外层代码
    + Promise对象抛出了错误，浏览器会报错，但是，后面的代码还会继续执行
4. catch方法返回的是什么？
    + <font color="#FF5983">catch方法返回的还是一个promise对象。</font>
    + catch后面仍然可以继续调用then方法。
    + catch里面也可以抛出错误，可以后面跟个catch进行捕获。

## Promise.prototype.finally()
1. Promise.prototype.finally() 什么时候用？举个使用Promise.prototype.finally的地方的实例？
    + 不管Promise对象最后的状态，都会执行的操作
    + 服务器使用一个Promise处理请求，处理完成后，用finally将服务器关掉。
        <pre>
        server.listen(port).then(function(){
            //...
        }).finally(server.stop)</pre>
2. finally方法的回调中，参数是什么样的？
    + finally的回调函数不接参数
    + so，finally里的操作和Promise对象的状态无关。不依赖Promise的执行结果

## Promise.all()
1. Promise.all()的用法是什么？接收的参数是什么？
    + Promise.all()将多个Promise实例，包装成一个新的Promise对象
    + 结合使用来说明接收的参数。`const p = Promise.all([p1,p2,p3]);`
        1. 参数不一定是数组，但是有一定都有Iterator接口。
        2. 返回的每个成员都是 Promise 实例。
2. `const p = Promise.all([p1,p2,p3]);`中p的状态如何决定的？
    + 由p1,p2,p3的状态共同决定，细分如下：
        1. p1,p2,p3状态全部为fulfilled时，p的状态才是fulfilled。此时，p1,p2,p3的返回值组成一个数组，此数组再传给p的回调函数。
        2. p1,p2,p3中有一个rejected，p的状态是rejected。此时第一个被reject的实例的返回值，会传递给p的回调函数。
        3. 如果p1，p2，p3的错误被catch住，那么传给p的就是fulfilled。原因是，catch返回的是个Promise实例。catch执行，说明此新实例fulfilled。 

## Promise.race()
1. Promise.all()的用法是什么？接收的参数是什么？
    + Promise.all()将多个Promise实例，包装成一个新的Promise对象
    + 接收的参数和Promise.all()一样
2. `const p = Promise.race([[p1,p2,p3]])`中p的状态怎么变？
    + p1，p2或p3有一个例子的状态改变了，p的状态跟着改变
    + 最先改变的p实例（如p1）的返回值，传递给p的回调函数
    + Promise.race方法的参数与Promise.all方法一样，如果不是 Promise 实例，就会先调用下面讲到的Promise.resolve方法，将参数转为 Promise 实例，再进一步处理

## Promise.resolve()
1. Promise.resolve()的作用？
    + Promise.resolve()将现有对象转化为Promise对象。
2. Promise.resolve()方法得参数有几种情况,分别怎么处理的?
    1. 参数是个Promise实例。此时不做任何修改，原封不动返回。
    2. 参数是thenable对象。
        * thenable对象是具有then方法得对象。
        * Promise.resolve会将此对象转化为Promise对象，并立即执行thenabel的then方法。
    3. 参数不是具有then方法的对象，或根本就不是对象
        * Promise.resolve方法返回一个新的 Promise 对象，状态为resolved
    4. 不带有任何参数
        * 不带参数时，直接返回一个resolved状态的Promise对象。
        * 立即resolve的Promise对象，是在本轮“事件循环”（event loop）的结束时执行，而不是下一轮“事件循环”的开始时执行。setTimeout是下一轮“循环”开始时执行，Promise.resolve是本轮“事件循环”结束时执行。其他顺序语句是立即执行。可以参照文中的例子。

## Promise.reject()
1. Promise.reject()的作用？
    + Promise.reject()返回一个新的 Promise 实例，该实例状态是rejected。
    + Promise.reject(thenable)方法的参数（比如thenable），会原封不动地作为reject的理由，变成后续方法的参数。比如：
        <pre>Promise.reject(thenable)
        .catch(e=>console.log(e))
        //此处的e和thenable完全相等</pre>

## Promise的应用
1. 加载图片
    + 加载完成或者失败，promise实例状态发生变化。
2. Generator函数与 Promise 的结合
    + (直接看阮大神文中实例)

## Promise.try()
1. Promise.try()是啥？
    + 是个提案，用promise.catch()捕获所有同步或异步的错误





